[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[dev]
  command = "next dev"
  port = 8888
  targetPort = 3000
  framework = "next"

# Next.js specific redirects
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Feature-specific redirects for vertical slice architecture

# Dogs feature
[[redirects]]
  from = "/api/dogs"
  to = "/.netlify/functions/dogs"
  status = 200

[[redirects]]
  from = "/api/dogs/:id"
  to = "/.netlify/functions/dog-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/dogs/:id/pedigree"
  to = "/.netlify/functions/dog-pedigree/:id"
  status = 200

[[redirects]]
  from = "/api/dogs/:id/upload-image"
  to = "/.netlify/functions/dog-upload-image/:id"
  status = 200

# DNA Testing feature
[[redirects]]
  from = "/api/dna-tests"
  to = "/.netlify/functions/dna-tests"
  status = 200

[[redirects]]
  from = "/api/dna-tests/:id"
  to = "/.netlify/functions/dna-test-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/dna-tests/parse"
  to = "/.netlify/functions/dna-test-parser"
  status = 200

# Health Clearances feature
[[redirects]]
  from = "/api/health-clearances"
  to = "/.netlify/functions/health-clearances"
  status = 200

[[redirects]]
  from = "/api/health-clearances/:id"
  to = "/.netlify/functions/health-clearance-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/health-clearances/verify"
  to = "/.netlify/functions/health-clearance-verification"
  status = 200

# Stud Services feature
[[redirects]]
  from = "/api/stud-services"
  to = "/.netlify/functions/stud-services"
  status = 200

[[redirects]]
  from = "/api/stud-services/:id"
  to = "/.netlify/functions/stud-service-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/stud-services/receptionist"
  to = "/.netlify/functions/stud-receptionist"
  status = 200

# Marketplace feature
[[redirects]]
  from = "/api/marketplace/products"
  to = "/.netlify/functions/marketplace-products"
  status = 200

[[redirects]]
  from = "/api/marketplace/products/:id"
  to = "/.netlify/functions/marketplace-product-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/marketplace/cart"
  to = "/.netlify/functions/marketplace-cart"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Import custom headers from netlify/headers.js
# Temporarily disabled due to package not found
# [[plugins]]
#   package = "netlify-plugin-inline-headers"
#   [plugins.inputs]
#     file = "netlify/headers.js"

# Netlify Build Settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
