@echo off
setlocal

rem Set Supabase environment variables
set NEXT_PUBLIC_SUPABASE_URL=https://jpnfefhrsehxzcrrozpw.supabase.co
set NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbmZlZmhyc2VoeHpjcnJvenB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjIwMDEsImV4cCI6MjA1OTI5ODAwMX0.lBfrSd1DnPlpTn0MQwJlNacGouCz2on6kqEzDvK6AGM
set SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbmZlZmhyc2VoeHpjcnJvenB3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzcyMjAwMSwiZXhwIjoyMDU5Mjk4MDAxfQ.IR4qhp_AHjA_FtGoZ3V-BnltXzbOb8sUouE9azdV7d8
set QUERY_API_KEY=qry_v1_p0bG0CCfnvivMjZ8oRS6zb1tfuErLqoBnqjIteNNThY
set SUPABASE_DB_PASSWORD=xavi7wx57aQQ
set SUPABASE_REGION=us-east-1
set SUPABASE_PROJECT_REF=jpnfefhrsehxzcrrozpw

rem Start the Supabase MCP server
node c:/Projects/bullyhub/mcp-supabase-server/src/index.js

endlocal
